export const routes = {
  wellcome: '/',
  login: '/login/:id',
  lostPassword: '/lostpassword',
  changePassword: '/changepassword/:id',
  dashboard: '/dashboard',
  lessonPlan: '/plan',
  news: '/news',
  newsbig: '/news/:id',
  documents: '/documents',
  polls: '/pools',
  pollsId: '/pools/:id',
  settings: '/settings',
  test: '/test',
  theme: '/theme',
};
